---
#TODO - break these down into
# common
# server
# client
- name: INSTALL | Ensure mariadb group exists
  group:
    name: "{{ mariadb_group }}"
    state: present

- name: INSTALL | Ensure mariadb user exists
  user:
    name: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    state: present

- name: INSTALL | Install mariadb-server package
  apt:
    name:
      - default-libmysqlclient-dev
      - mariadb-server
      - python-pymysql
    state: present

# PHP driver
- name: INSTALL | Install php-mysql package
  when: mariadb_phpdriver
  apt:
    name: php-mysql
    state: present
